name: package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release --verbosity normal -f net7.0
    - name: Pack DivertR
      run: |
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/DivertR ./src/DivertR/DivertR.csproj
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/DivertR.DynamicProxy ./src/DivertR.DynamicProxy/DivertR.DynamicProxy.csproj
    - name: Add Github Nuget Source
      run: dotnet nuget add source --username devodo --password ${{ secrets.PACKAGE_REPOSITORY_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/devodo/index.json"
    - name: Nuget Push
      run: |
        dotnet nuget push ./artifacts/DivertR/*.nupkg --api-key ${{ secrets.PACKAGE_REPOSITORY_TOKEN }} --source github
        dotnet nuget push ./artifacts/DivertR.DynamicProxy/*.nupkg --api-key ${{ secrets.PACKAGE_REPOSITORY_TOKEN }} --source github