name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal -f net6.0
    - name: Pack DivertR
      run: dotnet pack --no-build --no-restore --configuration Release --output ./artifacts ./src/DivertR/DivertR.csproj
    - name: Pack DivertR.DynamicProxy
      run: dotnet pack --no-build --no-restore --configuration Release --output ./artifacts ./src/DivertR.DynamicProxy/DivertR.DynamicProxy.csproj
    - name: Nuget Push
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
  
