name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release --verbosity normal -f net7.0
    - name: Pack DivertR
      run: |
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/DivertR ./src/DivertR/DivertR.csproj
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/DivertR.DynamicProxy ./src/DivertR.DynamicProxy/DivertR.DynamicProxy.csproj
    - name: Nuget Push
      run: |
        dotnet nuget push ./artifacts/DivertR/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        dotnet nuget push ./artifacts/DivertR.DynamicProxy/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}